# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('taughtby', models.CharField(max_length=50)),
                ('prerequisite', models.CharField(max_length=200)),
                ('course_language', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='enrolldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(default='2017-12-31')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
    ]
