# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170723_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.TextField(),
        ),
    ]
